# Generated by Django 4.2.23 on 2025-09-03 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_alter_profile_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('max_score', models.IntegerField(default=100)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeworks_app.subject')),
                ('teacher',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_homework',
                                   to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('teacher_comment', models.TextField(blank=True, null=True)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions',
                                               to='homeworks_app.homework')),
                ('student',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_submissions',
                                   to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty_type',
                 models.CharField(choices=[('percentage', 'Percentage'), ('points', 'Points')], max_length=15)),
                ('days_after_due', models.IntegerField()),
                ('penalty_value', models.FloatField()),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties',
                                               to='homeworks_app.homework')),
            ],
        ),
    ]
