# Generated by Django 3.2.13 on 2025-09-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(model_name='profile', name='group'),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(name='group', default='student', max_length=10),
        ),
    ]
